version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:lts-browsers
  working_directory: ~/repo

npm_cache: &npm_cache
  keys:
    - node_modules-{{ checksum "package-lock.json" }}
    - node_modules-

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *npm_cache
      - run: npm run lint
      - run: npm run ghpages
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist
      - run: bash <(curl -s https://codecov.io/bash)

  cypress:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          <<: *npm_cache
      - run:
          name: Run Cypress tests
          command: npm run test:ci:integration

  release:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: cd dist && npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - install
      - build:
          requires:
            - install
      - cypress:
          requires:
            - build
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - build
